language: node_js
node_js:
- 4
- 5
before_install:
- rvm install 2.2.2
install:
- npm install -g harp
- npm install
- gem install scss_lint
before_script:
- chmod +x ./scripts/deploy.sh
script:
- npm run lint
after_success:
- '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && npm run-script deploy'
env:
  global:
    secure: Ov2ULXOHHUp5lYVx0gl6t4pXgahRim4zJ2jvnl148rhieIf/qYfAmDmb5JRmrLOVwjUob4KDBxHLscBFoybMhxIGS3PnfDS9QFbyrLh+Ui/s5fTuNt+7a6CZdbGF/jEwuaYEw5f8+ytZYyMc1dSMJkbgCNGgsD9c8dGIJ0+jac/cgaYs5AkSHO2qyjW6+k6JXshlbev0J2xqNqYSHr5r/65S3aQEbSvOufJCB6OobG92Ijw81wY6m3t+dwmS03WzlPp4rigEtHKSoiZRTvw7EduHCkSom7l+hJarZ1HR2Cb84fGwgmaQeA7AeX5CLlCvvSs0LWnk2/kn+eXp9GjsT/gi7vP/LVI8Mg1n9EjPciflPE6YJ4tjw4K9hGyOjA4MgZHyUILSZDcNFB49TItN8YsJgyDnMurc+HB88xl7dqE5m2TMEANAPFTeSaC2zU039WwZcd44NQ7aVVS+gWKCqjtwWiqAC+KNAhMnIk2WKxk/Y1xrqI6YaDpvS6IS4jZn96Jg8XxLMFsUBwOQ/ju7StC3x2ePOnrRCVP9O1CuaCI6EJenmGorRy4QB5pRiJ1kxNvoEBZ8PAH7qNXmu/g3WsFSultW9iLOOWzZtIDTpDjvzSzjOFXT7xjtwyF9RJCmL2A4T5SzAOf0sE56/lAifa9gd8gii5+9eXWMsMbfvZY=
